gotapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('loans/', include('loans.urls')),
    path('payments/', include('payments.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loans/urls.py
from django.urls import path

from loans.views import loansAppView, loanAppCreate, loanAppDetail, LoansAppViews, loanView, loanAllView, loan_aff_view
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('list', loansAppView, name='index_loans_list'),
    path('addloans', loanAppCreate, name='add_apply_loan'),
    path('detail/<int:id_request>', loanAppDetail, name='detail_loan_app'),
    path('listall', login_required(LoansAppViews.as_view()), name='list_all_loans'),
    path('listloan', loanView, name='list_loan'),
    path('listloanall', loanAllView, name='list_loan_all'),
    path('listaffloans', loan_aff_view, name='list_aff_loans')
]

loans/models.py
from django.db import models

# Create your models here.
from users.models import User


class Loan_application(models.Model):
    description_loan = models.CharField(max_length=100)
    value = models.FloatField()
    fee_quantity = models.IntegerField()
    interest = models.FloatField(default=24)  # 27.66
    date_application = models.DateField(auto_now=True)
    status_application = models.CharField(default='En proceso..', max_length=100)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.description_loan


class Loan(models.Model):
    id_cobrador = models.ForeignKey(User, on_delete=models.CASCADE)
    id_request = models.ForeignKey(Loan_application, on_delete=models.CASCADE)
    balance = models.FloatField()
    is_completed = models.BooleanField(default=False)
    num_quotas_left = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id_cobrador}'

loans/forms.py
from django import forms
from .models import Loan_application, Loan
from users.models import User as Usuario


class LoanApplyForm(forms.ModelForm):
    description_loan = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    value = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fee_quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    interest_v = Loan_application._meta.get_field('interest').get_default()
    interest = forms.FloatField(disabled=True, initial=interest_v,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Loan_application
        fields = ['description_loan', 'value', 'fee_quantity', 'interest']


class LoanForm(forms.ModelForm):
    id_cobrador = forms.ModelChoiceField(queryset=Usuario.objects.filter(role__id=3),
                                         widget=forms.Select(attrs={'class': 'form-control'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Loan
        fields = ['id_cobrador', 'comment']

    """ def save(self, commit=True):
        loan = super().save(commit=False)
        print(loan)
        Loan_application.objects.filter(pk=loan.id_request.id).update(comment=loan.comment)
        if commit:
            loan.save()
        return loan
 """

loans/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from users.models import User as Usuario

# Create your views here.
from users.models import Role
from .models import Loan_application, Loan
from .forms import LoanApplyForm, LoanForm


class LoansAppViews(ListView):
    model = Loan_application
    queryset = Loan_application.objects.all()
    template_name = 'loans/loans_view.html'
    context_object_name = 'index_loans_list'


@login_required(login_url='login')
def loanAppCreate(request):
    user = User.objects.get(username=request.user).usuario
    if request.method == 'POST':
        form = LoanApplyForm(request.POST)
        if form.is_valid():
            newform = form.save(commit=False)
            newform.id_user = user
            newform.save()
            return redirect('index_loans_list')
    else:
        form = LoanApplyForm()
    # TEA = Loan_application.objects.all()[0].interest
    context = {'form': form}
    return render(request, 'loans/add_apply_loans.html', context)


@login_required(login_url='login')
def loansAppView(request):
    user = User.objects.get(username=request.user).usuario
    loansApp = Loan_application.objects.filter(id_user=user)
    context = {'index_loans_list': loansApp}
    return render(request, 'loans/loans_view.html', context)


@login_required(login_url='login')
def loanAppDetail(request, id_request):
    # loanapp = Loan_application.objects.get(pk=id_request)
    loanapp = get_object_or_404(Loan_application, pk=id_request)

    if request.method == 'POST':
        form = LoanForm(request.POST)
        if form.is_valid():
            Loan_application.objects.filter(pk=id_request).update(comment=request.POST['comment'])
            Loan_application.objects.filter(pk=id_request).update(status_application=request.POST['status'])
            if request.POST['status'] == 'Aprobado':
                newform = form.save(commit=False)
                newform.id_request = loanapp
                newform.balance = round(loanapp.value * pow((1 + float(loanapp.interest / 12) / 100), loanapp.fee_quantity), 2)
                newform.num_quotas_left = loanapp.fee_quantity
                newform.save()
            return redirect('list_all_loans')
    else:
        form = LoanForm()
    context = {'request': loanapp, 'form': form}
    return render(request, 'loans/detail.html', context)


@login_required(login_url='login')
def loanView(request):
    user = User.objects.get(username=request.user).usuario
    loan = Loan.objects.filter(id_request__id_user=user)
    context = {'loan': loan}
    return render(request, 'loans/loan_view.html', context)


def loanAllView(request):
    loan = Loan.objects.all()
    context = {'loan': loan}
    return render(request, 'loans/loan_view.html', context)


def loan_aff_view(request):
    user = User.objects.get(username=request.user).usuario
    loan = Loan.objects.filter(id_cobrador=user)
    context = {'loan': loan}
    return render(request, 'loans/loan_view.html', context)


def handler_not_found(request, exception):
    return render(request, '404.html')

templates/loans/add_apply_loans.html
{% extends 'base.html' %}
{% block title %} Add Apply Loans {% endblock %}

{% load static %}
{% block sidebar %}
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{% url 'home' %}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>GOTAPP</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{ user }}</h6>
                <span>{{ user.usuario.role }}</span>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'home' %}" class="nav-item nav-link "><i class="fa fa-th me-2"></i>Home</a>
            {% if user.groups.all.0|stringformat:'s' == 'prestamista' %}
                <a href="{% url 'list_all_loans' %}" class="nav-item nav-link "><i class="fa fa-chart-bar me-2"></i>Loan applications</a>
                <a href="{% url 'list_loan_all' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Loans</a>
            {% endif %}
            {% if user.groups.all.0|stringformat:'s' == 'cliente' %}
                <a href="{% url 'add_apply_loan' %}" class="nav-item nav-link active"><i class="fa fa-keyboard me-2"></i>Apply to a loan</a>
                <a href="{% url 'index_loans_list' %}" class="nav-item nav-link"><i class="far fa-file-alt me-2"></i>My loan requests</a>
                <a href="{% url 'list_loan' %}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>My loans</a>
            {% endif %}
            {% if user.groups.all.0|stringformat:'s' == 'cobrador' %}
                <a href="form.html" class="nav-item nav-link"><i class="fa fa-th me-2 "></i>Affiliated loans</a>
            {% endif %}
        </div>
    </nav>
</div>
{% endblock %}

{% block content %}
    <div class="row d-flex justify-content-center">
        <div class="col-sm-12 col-xl-6">
            <div class="bg-light rounded h-100 p-4">
                <form action="" method="POST">
                    {% csrf_token %}
                    <h5 class="mb-4">Loan application</h5>
                    <div class="form-floating mb-3">
                        <textarea name="description_loan" class="form-control" placeholder="Loan description"
                            id="id_description_loan" style="height: 150px;" required></textarea>
                        <label for="id_description_loan">Loan description</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="number" class="form-control" id="id_value" name="value"
                            placeholder="Value" required>
                        <label for="id_value">Value</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="number" class="form-control" id="id_fee_quantity" name="fee_quantity"
                            placeholder="Fee quantity" required>
                        <label for="id_fee_quantity">Fee quantity</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="id_interest" name="interest"
                            placeholder="TEA (%)" value={{ form.interest.value }} disabled>

                        <label for="id_interest">TEA (Effective Annual Rate)</label>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{#<div class="col-md-6 grid-margin stretch-card">#}
{#    <div class="card">#}
{#        <div class="card-body">#}
{#            <h4 class="card-title">Loan application</h4>#}
{#            <p class="card-description"> Fill the form to ask for a loan </p>#}
{##}
{#            <form method="post" novalidate>#}
{#                {% csrf_token %}#}
{#                {% for field in form.visible_fields %}#}
{#                    <div class="form-group">#}
{#                        <label for="{{ field.id_for_label }}" class="">{{field.label}}</label>#}
{#                        {{ field }}#}
{#                        {% for error in field.errors %}#}
{#                            <span class="help-block" style="color:red">{{error}}</span>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                {% endfor %}#}
{##}
{#                <button type="submit" class="btn btn-primary mr-2">Submit</button>#}
{#                <button class="btn btn-dark">Cancel</button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#</div>#}


{#                    <form class="forms-sample" method="post">#}
{#                        {% csrf_token %}#}
{#                        <div class="form-group">#}
{#                            <label for="exampleInputUsername1">Username</label>#}
{#                            <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Username">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <label for="exampleInputEmail1">Email address</label>#}
{#                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <label for="exampleInputPassword1">Password</label>#}
{#                            <input type="password" class="form-control" id="exampleInputPassword1"#}
{#                                   placeholder="Password">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <label for="exampleInputConfirmPassword1">Confirm Password</label>#}
{#                            <input type="password" class="form-control" id="exampleInputConfirmPassword1"#}
{#                                   placeholder="Password">#}
{#                        </div>#}
{#                        <div class="form-check form-check-flat form-check-primary">#}
{#                            <label class="form-check-label">#}
{#                                <input type="checkbox" class="form-check-input"> Remember me </label>#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-primary mr-2">Submit</button>#}
{#                        <button class="btn btn-dark">Cancel</button>#}
{#                    </form>#}

templates/loans/detail.html
{% extends 'base.html' %}
{% block Title %} Detail {% endblock %}
{% block content %}
<div class="container">
<div>
    Aprobar prestamo
</div>
    <div class="'row justify-content-md-center pt-5">
        <form action={% url 'detail_loan_app' request.id %} method="POST">
            {% csrf_token %}
            Seleccionar Cobrador
            <div class="'col-md-8">
                <div class="col-12"><h1>{{form.id_cobrador}}</h1></div>
                <br/>
                <br/>
                Comentario sobre prestamo
                <div class="col-12"><p><b>{{form.comment}}</b></p></div>

            Descripcion de prestamo: {{request}}
            <div class="col-12">Solicitante: {{request.id_user.name}}</div>
            <div class="col-12"><p>Valor prestamo solicitado: {{request.value}}</p></div>

            {% if request.status_application|stringformat:'s' == 'En proceso..' %}
                <button name="status" type="submit" class="btn btn-success" value="Aprobado">Aprobar</button>
                <button name="status" type="submit" class="btn btn-danger" value="Rechazado">Rechazar</button>
            {% endif %}
        </form>
            <a href="{% url 'list_all_loans' %}" class="btn btn-secondary">Back</a>

    </div>
</div>
{% endblock %}

templates/loans/loan_view.html
{% extends 'base.html' %}
{% block title %}
    List of loans
{% endblock %}

{% load static %}
{% block sidebar %}
    <!-- Sidebar Start -->
    <div class="sidebar pe-4 pb-3">
        <nav class="navbar bg-light navbar-light">
            <a href="{% url 'home' %}" class="navbar-brand mx-4 mb-3">
                <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>GOTAPP</h3>
            </a>
            <div class="d-flex align-items-center ms-4 mb-4">
                <div class="position-relative">
                    <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt=""
                         style="width: 40px; height: 40px;">
                    <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                </div>
                <div class="ms-3">
                    <h6 class="mb-0">{{ user }}</h6>
                    <span>{{ user.usuario.role }}</span>
                </div>
            </div>
            <div class="navbar-nav w-100">
                <a href="{% url 'home' %}" class="nav-item nav-link "><i class="fa fa-th me-2"></i>Home</a>
                {% if user.groups.all.0|stringformat:'s' == 'prestamista' %}
                    <a href="{% url 'list_all_loans' %}" class="nav-item nav-link "><i class="fa fa-chart-bar me-2"></i>Loan
                        applications</a>
                    <a href="{% url 'list_loan_all' %}" class="nav-item nav-link active"><i class="fa fa-th me-2"></i>Loans</a>
                {% endif %}
                {% if user.groups.all.0|stringformat:'s' == 'cliente' %}
                    <a href="{% url 'add_apply_loan' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Apply
                        to a loan</a>
                    <a href="{% url 'index_loans_list' %}" class="nav-item nav-link"><i
                            class="far fa-file-alt me-2"></i>My loan requests</a>
                    <a href="{% url 'list_loan' %}" class="nav-item nav-link active"><i class="fa fa-table me-2"></i>My
                        loans</a>
                {% endif %}
                {% if user.groups.all.0|stringformat:'s' == 'cobrador' %}
                    <a href="{% url 'list_aff_loans' %}" class="nav-item nav-link"><i class="fa fa-th me-2 "></i>Affiliated loans</a>
                {% endif %}
            </div>
        </nav>
    </div>
{% endblock %}

{% block content %}
    <div class="my-3">
        <h1 class="text-center">List of loans </h1>

        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Balance</th>
                <th>Remaining quotas</th>
                <th>Debt Collector</th>
                <th>Is completed</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% if loan %}
                {% for item in loan %}
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.id_request }}</td>
                        <td>{{ item.balance }}</td>
                        <td>{{ item.num_quotas_left }}</td>
                        <td>{{ item.id_cobrador }}</td>
                        <td>
                            {% if item.is_completed %}
                                <img src="{% static 'img/icon-yes.svg' %}" alt="True">
                            {% else %}
                                <img src="{% static 'img/icon-no.svg' %}" alt="True">
                            {% endif %}
                        </td>
                        <td>
                            {% if user.groups.all.0|stringformat:'s' == 'cliente' %}
                                {% if not item.is_completed %}
                                    <a href="{% url 'create_payment' item.id %}" class="btn btn-outline-success"> Pay</a>
                                {% endif %}
                            {% endif %}
                            <a href="{% url 'list_payment' item.id %}" class="btn btn-outline-success"> See payments</a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <th>No data found</th>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/loans/loans_view.html
{% extends 'base.html' %}
{% block title %}
    List of loans applications
{% endblock %}

{% load static %}
{% block sidebar %}
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{% url 'home' %}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>GOTAPP</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{ user }}</h6>
                <span>{{ user.usuario.role }}</span>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'home' %}" class="nav-item nav-link "><i class="fa fa-th me-2"></i>Home</a>
            {% if user.groups.all.0|stringformat:'s' == 'prestamista' %}
                <a href="{% url 'list_all_loans' %}" class="nav-item nav-link active"><i class="fa fa-chart-bar me-2"></i>Loan applications</a>
                <a href="{% url 'list_loan_all' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Loans</a>
            {% endif %}
            {% if user.groups.all.0|stringformat:'s' == 'cliente' %}
                <a href="{% url 'add_apply_loan' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Apply to a loan</a>
                <a href="{% url 'index_loans_list' %}" class="nav-item nav-link"><i class="far fa-file-alt me-2"></i>My loan requests</a>
                <a href="{% url 'list_loan' %}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>My loans</a>
            {% endif %}
            {% if user.groups.all.0|stringformat:'s' == 'cobrador' %}
                <a href="form.html" class="nav-item nav-link"><i class="fa fa-th me-2 "></i>Affiliated loans</a>
            {% endif %}
        </div>
    </nav>
</div>
{% endblock %}

{% block content %}
    <div class="my-3">
        <h1 class="text-center">List of loans applications</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Description</th>
                    <th>Value</th>
                    <th>Quotas (fees)</th>
                    <th>Interest</th>
                    <th>Date Application</th>
                    <th>Status Application</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                {% if index_loans_list %}
                    {% for item in index_loans_list %}
                        <tr>
                            <th scope="row">{{ item.id }}</th>
                            {% if user.usuario.role|stringformat:"s" == "Prestamista" %}
                                <td><a href="{% url 'detail_loan_app' item.id %}">{{ item.description_loan | capfirst }}</a></td>
                            {% else %}
                                <td>{{ item.description_loan | capfirst }}</td>
                            {% endif %}
                            <td>{{ item.value }}</td>
                            <td>{{ item.fee_quantity }}</td>
                            <td>{{ item.interest }}</td>
                            <td>{{ item.date_application }}</td>
                            <td>{{ item.status_application }}</td>
                            <td>{{ item.comment }}</td>

                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <th>No data found</th>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}